[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13

[colors]
primary.background = "#ffffff"
primary.foreground = "#333333"

[colors.normal]
black = "#000000"
red = "#cc0000"
green = "#116432"
yellow = "#b58900"
blue = "#0344AE"
magenta = "#750154"
cyan = "#52529e"
white = "#777777"

[colors.bright]
black = "#000000"
red = "#cc0000"
green = "#116432"
yellow = "#b58900"
blue = "#0344AE"
magenta = "#750154"
cyan = "#52529e"
white = "#777777"
