- name: "Check pyenv available"
  shell: pyenv --version 2>&1
  register: pyenv_result
  failed_when: "pyenv_result.rc not in [0, 127]"
  tags:
    - install
    - python
    - neovim

- name: "Install Pyenv"
  shell: "curl -sS -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash"
  when: "pyenv_result.rc == 127"
  tags:
    - install
    - python
    - neovim

- name: "Install Python"
  shell: 'pyenv install 3.10.10 && pyenv global 3.10.10 && eval "$(pyenv init -)"'
  when: "pyenv_result.rc == 127"
  tags:
    - install
    - python
    - neovim

- name: "Install Python-Pyright"
  ansible.builtin.pip:
    name: pyright
  tags:
    - install
    - neovim
    - python

- name: "Install Python-Formatter (black)"
  ansible.builtin.pip:
    name: black
  tags:
    - install
    - neovim
    - python
