theme = "rasmus"

[editor]
color-modes = true
cursorline = true
line-number = "relative"
mouse = true
rulers = [120]


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "|"

[editor.lsp]
display-inlay-hints = true

[keys.normal]                                                                                                                                                                                                                                                                                                                                                                                                                                         
C-h = "jump_view_left"                                                                                                                                                                                                                                                                                                                                                                                                                           
C-l = "jump_view_right"                                                                                                                                                                                                                                                                                                                                                                                                                         
C-k = "jump_view_up"                                                                                                                                                                                                                                                                                                                                                                                                                               
C-j = "jump_view_down" 
space.G = ":sh kitty @ launch --cwd current --type overlay-main --no-response lazygit"
space.e = ":sh kitty @ launch --cwd current --type overlay-main --no-response joshuto"
