- name: "Install stow"
  become: true
  apt:
    name: ["stow"]
  tags:
    - install
    - dotfiles

- name: "Clone dotfiles" 
  ansible.builtin.git:
    repo: 'https://github.com/mlorthiois/dotfiles'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
  ignore_errors: yes
  tags:
    - install
    - dotfiles

- name: "Stow dotfiles"
  shell: |
    for f in $(ls -d */ | grep -v "ansible\|fonts"); do
      stow -D $f
      stow $f
    done
  tags:
    - install
    - dotfiles

- name: "Install zsh plugins"
  ansible.builtin.git:
    repo: 'https://github.com/{{ item }}'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/zsh/{{ item }}"
  ignore_errors: yes
  tags:
    - install
    - dotfiles
  loop:
    - zsh-users/zsh-autosuggestions
    - zdharma-continuum/fast-syntax-highlighting
